Deps: Update faithfuls <easy-as-pypi>
- Source: easy-as-pypi @ 350aee09df60 [1.1.11a7~42]

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/doblabs/easy-as-pypi/blob/release/bin/update-faithful

diff --git a/.github/workflows/ci-tags-wrangle.yml b/.github/workflows/ci-tags-wrangle.yml
--- a/.github/workflows/ci-tags-wrangle.yml
+++ b/.github/workflows/ci-tags-wrangle.yml
@@ -13,6 +13,14 @@ on:
     # - So if inputs left unsaid, means caller just wants current state.
 
     inputs:
+      # Determines which branch to use, default or pre-release.
+      # - 'HEAD'- and 'project'-scoped tags are branch-specific.
+      prerelease:
+        type: boolean
+        required: true
+
+      # ***
+
       # If tagged on HEAD, don't do current cascade.
       inhibit-cascade:
         type: string
@@ -33,7 +41,7 @@ on:
       #
       # These tags are set per-project when they start (update-deps.yml), and
       # cleared when they pass along the cascading stick (by release-smoke-test.yml,
-      # after calling update-cascade.yml).
+      # after calling spread-updates.yml).
 
       # If tagged on HEAD and not "true", skip bin/update-poetry this cascade.
       cascade-updatedeps:
@@ -46,12 +54,28 @@ on:
       # If tagged on HEAD, determines versioning increment this cascade.
       # - Use "skip" to not version, and also to not release any projects.
       cascade-versioning:
-        # Opts: 'alpha', 'patch', 'least', or 'skip';
+        # Opts: 'alpha', 'patch', or 'skip';
         #       or 'false' to remove the tag,
         #       or '' to merely read the tag.
         type: string
         required: false
       delete-cascade-versioning:
+        type: boolean
+        default: false
+
+      # *** User-managed tags
+
+      inhibit-alpha:
+        type: string
+        required: false
+      delete-inhibit-alpha:
+        type: boolean
+        default: false
+
+      inhibit-patch:
+        type: string
+        required: false
+      delete-inhibit-patch:
         type: boolean
         default: false
 
@@ -72,6 +96,18 @@ on:
       old-cascade-versioning:
         description: "The previous/maybe current ci-cascade-versioning value"
         value: ${{ jobs.wrangle-ci-tags.outputs.old-cascade-versioning }}
+      # The alpha and patch inhibitors are prerelease-related,
+      # so the raw values are not interesting to callers:
+      #   old-inhibit-alpha:
+      #     description: "The previous/maybe current ci-inhibit-alpha value"
+      #     value: ${{ jobs.wrangle-ci-tags.outputs.old-inhibit-alpha }}
+      #   old-inhibit-patch:
+      #     description: "The previous/maybe current ci-inhibit-patch value"
+      #     value: ${{ jobs.wrangle-ci-tags.outputs.old-inhibit-patch }}
+      # - But the calculated value for the current branch is interesting:
+      old-inhibit-release-pypi:
+        description: "Either old-inhibit-alpha or old-inhibit-patch per prerelease"
+        value: ${{ jobs.wrangle-ci-tags.outputs.old-inhibit-release-pypi }}
 
 # ***
 
@@ -96,19 +132,53 @@ jobs:
       old-cascade-versioning: "${{
         steps.wrangle-ci-tags.outputs.old_cascade_versioning
       }}"
+      old-inhibit-alpha: "${{
+        steps.wrangle-ci-tags.outputs.old_inhibit_alpha
+      }}"
+      old-inhibit-patch: "${{
+        steps.wrangle-ci-tags.outputs.old_inhibit_patch
+      }}"
+      old-inhibit-release-pypi: "${{
+        steps.compute-ci-tags.outputs.old_inhibit_release_pypi
+      }}"
 
     steps:
-      - name: Checkout repo @ ${{ inputs.head-ref }}
+      - name: Checkout repo
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.repository.default_branch }}
-          # We can `fetch-depth: 0` or `fetch-tags: 'true'` for all tags.
-          # - We don't need history, just tags.
-          # - The docs don't say why it matters. It's left to the reader
-          #   to assume that fetching history and/or tags is more resource
-          #   intensive and/or degrades job performance. *Just saying.*
-          fetch-depth: 1
-          fetch-tags: true
+          # If pre-release, use alternative branch if defined.
+          ref: ${{
+            inputs.prerelease
+            && vars.PRERELEASE_BRANCH
+            || github.event.repository.default_branch }}
+          # Use `fetch-depth: 0` to fetch all tags.
+          # - Note that `fetch-tags: 'true'` only fetches branch tags.
+          # - I didn't see this in GHA docs, just something I learned.
+          fetch-depth: 0
+
+      # ***
+
+      # NODRY: See similar steps: ci-tags-wrangle.yml, update-merged.yml
+      - name: Prepare committer
+        run: |
+          assert_git_email_known_ci () {
+            test -n "${UPDEPS_USER_EMAIL}" \
+              && return 0 || true
+
+            >&2 echo "ERROR: Please set UPDEPS_USER_EMAIL " \
+              "organization or project variable"
+
+            exit 1
+          }
+          assert_git_email_known_ci
+
+          git config user.email "${UPDEPS_USER_EMAIL}"
+          git config user.name \
+            "${UPDEPS_USER_NAME_CI_TAGS:-${UPDEPS_USER_NAME:-release-bot}}"
+        env:
+          UPDEPS_USER_EMAIL: ${{ vars.UPDEPS_USER_EMAIL }}
+          UPDEPS_USER_NAME: ${{ vars.UPDEPS_USER_NAME }}
+          UPDEPS_USER_NAME_CI_TAGS: ${{ vars.UPDEPS_USER_NAME_CI_TAGS }}
 
       # ***
 
@@ -125,3 +195,52 @@ jobs:
           EAPP_DELETE_CASCADE_UPDATEDEPS: ${{ inputs.delete-cascade-updatedeps }}
           EAPP_CASCADE_VERSIONING: ${{ inputs.cascade-versioning }}
           EAPP_DELETE_CASCADE_VERSIONING: ${{ inputs.delete-cascade-versioning }}
+          EAPP_INHIBIT_ALPHA: ${{ inputs.inhibit-alpha }}
+          EAPP_DELETE_INHIBIT_ALPHA: ${{ inputs.delete-inhibit-alpha }}
+          EAPP_INHIBIT_PATCH: ${{ inputs.inhibit-patch }}
+          EAPP_DELETE_INHIBIT_PATCH: ${{ inputs.delete-inhibit-patch }}
+
+      # ***
+
+      - name: Compute CI tags
+        id: compute-ci-tags
+        run: |
+          out_name="old_inhibit_release_pypi"
+          old_tag_value="${{ false
+            || (inputs.prerelease
+                && steps.wrangle-ci-tags.outputs.old-inhibit-alpha == 'true'
+                && 'true')
+            || (!inputs.prerelease
+                && steps.wrangle-ci-tags.outputs.old-inhibit-patch == 'true'
+                && 'true')
+            || 'false' }}"
+          echo "${out_name}=${old_tag_value}" >> "${GITHUB_OUTPUT}"
+
+          echo "GITHUB_OUTPUT:"
+          cat "${GITHUB_OUTPUT}" | sed 's/^/  /'
+
+      # ***
+
+      - name: Trace vars
+        run: |
+          echo "old-inhibit-cascade: ${{
+            steps.wrangle-ci-tags.outputs.old_inhibit_cascade
+          }}"
+          echo "old-inhibit-forever: ${{
+            steps.wrangle-ci-tags.outputs.old_inhibit_forever
+          }}"
+          echo "old-cascade-updatedeps: ${{
+            steps.wrangle-ci-tags.outputs.old_cascade_updatedeps
+          }}"
+          echo "old-cascade-versioning: ${{
+            steps.wrangle-ci-tags.outputs.old_cascade_versioning
+          }}"
+          echo "old-inhibit-alpha: ${{
+            steps.wrangle-ci-tags.outputs.old_inhibit_alpha
+          }}"
+          echo "old-inhibit-patch: ${{
+            steps.wrangle-ci-tags.outputs.old_inhibit_patch
+          }}"
+          echo "old-inhibit-release-pypi: ${{
+            steps.compute-ci-tags.outputs.old_inhibit_release_pypi
+          }}"
